### ISSUE TITLE
Adopt pyproject.toml in place of setup.cfg

### ISSUE THREAD

**Issue by goatsweater** [StatCan/datascience-cookiecutter#46]
As of `setuptools` v61 and [PEP 621](https://peps.python.org/pep-0621/) it is possible to hold project configuration within `pyproject.toml` files. Documentation on this approach is [available from setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html).

Prior to making any changes I'd like to get feedback on the idea of adopting this now. Impact of the change in unclear as we don't know how many projects have been derived from the cookiecutter.

## Benefits

* We are already leveraging this file to control the package builds as well as `pytest` configuration.
* `pyproject.toml` has native support for centralized version numbers through what it calls [dynamic metadata](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata). Could help simplify our version management.
* This is the future, so adopting it means getting projects derived from the cookiecutter onto the best practices early.

## Considerations

* `[tool.setuptools]` options are still considered beta. They work, but the syntax under this heading may changes in the future.
  * By using pinned versions of setuptools we can minimize the impact of this but we would still need to track/manage any changes.
* Unknown how `cruft update` will handle this change.
* `flake8` has not yet moved away from `setup.cfg` so the options need to be moved somewhere.
* It is still early days in support, so adopting it may mean certain incompatibilities/workarounds for a short time (`falke8` is one example).

/cc @Collinbrown95 @asolis @ToucheSir

**Comment by ToucheSir** [comment]
One way to solve the flake8 problem could be to switch to https://github.com/charliermarsh/ruff. It allows for configuration via pyproject.toml and seems generally impressive performance + feature-wise.

**Comment by goatsweater** [comment]
Good find! I don't remember which extensions to flake8 we use, if any, but it won't be many. Could potentially replace a couple of the other items we have in pre-commit and centralize their config as well.

**Comment by goatsweater** [comment]
It also occurs to me that adopting `pyproject.toml` can help with the issues of trying to keep conda environments in sync by adopting the tooling proposed in #36.
