### ISSUE TITLE
Update actions to node v16

### ISSUE THREAD

**Issue by goatsweater** [StatCan/datascience-cookiecutter#53]
It seems GitHub actions have deprecated node v12 as the following message is appearing in build/tests:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

The relevant actions need to be reviewed and upgraded to supported versions.

**Comment by ToucheSir** [comment]
I recently learned that we can also automate keeping our GH Actions up-to-date with https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot.
